services:
  web: 
    image: nginx
    volumes:
      - ./servidor-web:/usr/share/nginx/html
    ports:
      - 8080:80

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - 4442:4442
      - 4443:4444
      - 4444:4444

  node-chrome:
    image: selenium/node-chrome
    deploy:
      replicas: 10
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442   
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  node-firefox:
    image: selenium/node-firefox
    deploy:
      replicas: 1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  node-edge:
    image: selenium/node-edge
    deploy:
      replicas: 1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443